// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrnfvlbnncqusrkkcchw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhybmZ2bGJubmNxdXNya2tjY2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTgwNzgsImV4cCI6MjA3MDU3NDA3OH0.TEw8zcm7ScwAwPjWyoK2ydvgKxflPeFiArWZFQCwXzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});